spring:
  application:
    name: ethos-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:8092/ethos
  jpa:
    hibernate:
      ddl-auto: update
    show-sql:
      true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9000